### ISSUE TITLE
Installer can't handle passwords that contain shell special characters

### ISSUE THREAD

**Issue by nshalman** [joyent/sdc#34]
In theory passwords in the config file should perhaps be enclosed inside single quotation marks with any single quotation marks in the password escaped.

Super low priority.

**Comment by appletalk** [comment]
With still new script it still returns an error if using a password for root and admin that ends with a backtick `

**Comment by lloydde** [comment]
@appletalk meaning you tried @bahamat 's fix? or meaning you did an install most recently?

**Comment by bahamat** [comment]
It's worth noting that my fix was only for single quotes. I had hoped that by escaping single quotes and enclosing the entire password value in single quotes that we'd avoid any other interpolation later. Since @appletalk used a backtick my fix didn't really work as I had hoped. We'll need something that more intelligently escapes anything special.

**Comment by sodre** [comment]
I had the a similar issue when my password included the left paranthesis '('

**Comment by trentm** [comment]
Should be fixed now in https://smartos.org/bugview/HEAD-2279

**Comment by trentm** [comment]
with this commit: https://github.com/joyent/sdc-headnode/commit/f987f1d0d0c1036ebb006c69b3e44092200fbced
