### ISSUE TITLE
Documentation? Forgotten how to write?

### ISSUE THREAD

**Issue by MarioColuzzi** [joyent/sdc#46]
Hello,

Pretty disgusting the instructions I'd say. Maybe it is clear for you how this software works but the rest of us?

The instructions do not say ANYTHING useful in how to install and run it. Do I need to install a SmartOS into a "virgin" PC or not? Does this tool runs already an existing VM in Win or Linux?

Remember if you want your software to be successful SEND YOUR MESSAGE ACROSS CLEARLY otherwise is only a garage project.

Mario

About me: with 25 years experience working as SCM Manager Consultant for large IT organisations with

Motto: If it the tool doesn't hit, I scrap it

**Comment by notmatt** [comment]
@MarioColuzzi I'm sorry if it's somewhat buried under the intro and exposition, but I suspect what you're looking for is in the [Getting Started section|https://github.com/joyent/sdc/issues/46] of the project's README.md. There are two options to try it out, the "[Cloud on a Laptop|https://github.com/joyent/sdc#cloud-on-a-laptop-coal]" option using VMWare (on OSX, Windows or Linux) - good for a first look or evaluation, and instructions for using [physical hardware|https://github.com/joyent/sdc#installing-sdc-on-a-physical-server], which includes a number of links to recommended hardware and Joyent's own BOMs.

**Comment by MarioColuzzi** [comment]
@notmatt A picture is worth a 1000s words. it would be nice to talk the same language to have the information clearly understood, and a picture does exactly that because it breaks the "language barrier". The instructions may be clear to whom wrote them but not to whom is reading them.

Besides all the above. I have to scrap this product from my list, from the lack of instructions to VM Image not working, from unclear objectives to usefulness.

I must focus my search on something else without losing time and patience.

#nooffence #sorry  

NOTE: the VM Image supplied DOES NOT work, it loops on the setting because it doesn't find some files on temp.

**Comment by davepacheco** [comment]
Sorry for the rough user experience.  As you point out, it can be difficult for people working closely on a project to identify what's not obvious to new users.  That said, we've had a number of users successfully set up SDC on their own.  So the more concrete your feedback, the better we'll be able to improve the software so that other users will have a smoother experience.  This would be most appreciated.  For example: when you say the image does not work, are you talking about the VMware image?  Did it successfully boot in VMware?  Did it print something to the VMware console?  Did it report an error?  Were you able to log into it?  If it was the instructions that were unclear, did you have trouble finding the Getting Started section, or was that section unclear?  Were you trying the CoaL instructions?  Which step(s) were unclear?  Thanks!
